env:
  browser: true
  es2021: true
  jest: true
extends:
    - 'airbnb-typescript'
    - 'airbnb/hooks'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  'linebreak-style': 'off'
  'prettier/prettier':
    - 'error'
    - endOfLine: 'auto'
  'react/prefer-stateless-function': 'off'
  'react/require-default-props': 'off'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
